[project]
name = "saved-and-deployed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.123.9",
    "scikit-learn>=1.7.2",
    "uvicorn>=0.38.0",
]
